### ISSUE TITLE
Encrypt key backups during PIN creation / changes

### ISSUE THREAD

**Issue by gurnec** [schildbach/bitcoin-wallet#186]
The "Update mobile environment score" issue at the bitcoin.org repo got me thinking about this one.... The proposed environment score reads:

> mobiles are usually easier to steal or lose...using a strong passphrase...can make it harder to steal your bitcoin

The current passphrase/PIN feature doesn't encrypt the key-backup-protobuf files in the private data store. Although this isn't a problem (at the moment AFAIK) from a malware point of view, from a stolen or lost mobile point of view it seems more dangerous.

I really don't know just how dangerous this is (it would relate to the market share of rootable mobiles I suppose), but IMHO it should be addressed before it becomes a problem....

**Comment by schildbach** [comment]
Since version 4.14, there are no `key-backup-protobuf.<day>` files any more and `key-backup-protobuf` files are refreshed with each set or change PIN operation.

**Comment by gurnec** [comment]
Great improvements, thanks!

**Comment by opies32765** [comment]
Gurnec

I have an issue i need help with on btcrecover...can i send you a message to see if you can help me figure it out ?

**Comment by btc2dogecom** [comment]
> Gurnec
> 
> I have an issue i need help with on btcrecover...can i send you a message to see if you can help me figure it out ?

we bruteforce for you.
