### ISSUE TITLE
BIP70 PaymentRequest file : Fetching signature failed, cannot recognize input

### ISSUE THREAD

**Issue by tchoulihan** [schildbach/bitcoin-wallet#200]
I'm trying to set up a payment request at a URL, but the bitcoin testnet wallet is giving me an error only for my specific .bitcoinpaymentrequest file, but not ones generated [here](https://bitcoincore.org/~gavin/createpaymentrequest.php) at gavin's payment request generator. 

The error I get in the testnet wallet is a popup window that says:
>FETCHING SIGNATURE FAILED
>cannot recognize input: null

I've been comparing my payment request file, with those of gavin's generator, using 
`org.bitcoinj.tools.PaymentProtocolTool.main(new String[]{bitcoin_url);`
and they look exactly the same. The URL is correctly encoded, and the wallet isn't telling me it can't find the .bitcoinpaymentrequest file.

Does anyone know what fetching signature failed means? my pki type is 'none', so I'm not sure why it would be looking for a signature.

Just for reference, here's an output of my paymentrequest file:
```
22:07:21.666 [main] DEBUG org.bitcoinj.uri.BitcoinURI - Attempting to parse 'bitcoin:myTYR6DG7V3EQvwHLDYbnP4BuwVTKHwg1h?r=http%3A%2F%2F96.28.13.51%3A4567%2Fpayment_requests%2Forder_1.bitcoinpaymentrequest&amount=0.00451541' for any
Bitcoin payment request, version 1
Date: Mon Jan 12 11:47:23 EST 2015


payment_details_version: 1
pki_type: "none"
serialized_payment_details: "\n\004test\022\037\b\325\307\033\022\031v\251\024\204\347\354\031\004\306z\3563F\343\275\216]\227\271f\345\016\232\210\254\030\233\365\317\245\005"

network: "test"
outputs {
  amount: 451541
  script: "v\251\024\204\347\354\031\004\306z\3563F\343\275\216]\227\271f\345\016\232\210\254"
}
time: 1421081243
```

**Comment by schildbach** [comment]
Did you try reading the PR with bitcoin-qt? Also, can you have a look at "adb logcat"? I think there should be more useful messages there.

Does your web server set a content-type of "application/bitcoin-paymentrequest"? Your server is currently unreachable, so I cannot check myself.

**Comment by tchoulihan** [comment]
I tested the URI with bitcoin-qt, and it worked fine.

I'm looking at the logcat, and grepping for a lot of different things, and finally found a message:

```
I/RequestPaymentRequestTask(31705): [backgroundThread] trying to request payment request from http://96.28.13.51:4567/payment_requests/order_1.bitcoinpaymentrequest
I/SendCoinsFragment(31705): [main] got PaymentIntent[BIP21,[Output[0.0018,myTYR6DG7V3EQvwHLDYbnP4BuwVTKHwg1h]],null,paymentRequestUrl=http://96.28.13.51:4567/payment_requests/order_1.bitcoinpaymentrequest]
```

But no messages, logging level verbose. Its still telling me
>FETCHING SIGNATURE FAILED
>cannot recognize input: null

I don't think there's a content type on that URL, since its just pointing to a static .bitcoinpaymentrequest file. I tried setting a content type on a different URL, and redirecting the response to the file, but I get the message:
>cannot recognize input: http 304

Suggesting that it can't handle redirects. 

I'll leave the web server up and running, so here's the [link](http://96.28.13.51:4567/payment_requests/order_1.bitcoinpaymentrequest)

and the URI : 

>bitcoin:myTYR6DG7V3EQvwHLDYbnP4BuwVTKHwg1h?r=http%3A%2F%2F96.28.13.51%3A4567%2Fpayment_requests%2Forder_1.bitcoinpaymentrequest&amount=0.00451541

**Comment by schildbach** [comment]
Right, the URL doesn't come with a content-type. Try setting the correct type as per BIP71.

**Comment by tchoulihan** [comment]
That's because its a static file resource, ending in .bitcoinpaymentrequest, which is why I suppose bitcoin-qt is able to parse it. 

I've tried a lot of different ways to return a payment request proto as a string resource, but none of them has worked, so I just used a file located at that resource instead. The web service I'm using is having some trouble returning binary data except as a file resource. Neither bitcoin-qt, nor the android wallet can handle redirects either, unfortunately. 

The protos.writeTo methods seem only to work with file resources. So far they've failed me with ByteArrayOutputStreams.

**Comment by tchoulihan** [comment]
@schildbach I figured out a way to get it working with my web service. I'll write it here just for reference, at least with java spark:
```
response.type("application/bitcoin-paymentrequest");
response.header("Content-Transfer-Encoding", "binary");		

HttpServletResponse raw = response.raw();

PaymentRequest pr = PaymentRequest.parseFrom(bytes);
pr.writeTo(raw.getOutputStream());
				
raw.getOutputStream().flush();
raw.getOutputStream().close();

return res.raw();
```

I still think it would be a good idea for the android-wallet to be able to parse static resources, with the correct extension at least, as bitcoin-qt does. You can close out this ticket anytime.

**Comment by schildbach** [comment]
For an HTTP client, there is no such differentiation into static and dynamic resources. It's just an HTTP resource. Most web servers have a way to configure the content-type of static resources, like a filename to content-type mapping.

**Comment by tchoulihan** [comment]
Ah. The webservice I was using did not have the ability to configure the content type of a static resource, you just expose a folder.  

Either way, setting the content-type to what you said above worked great, thanks!
