### ISSUE TITLE
There is a new address provided on every "request coins"

### ISSUE THREAD

**Issue by hrhristov** [schildbach/bitcoin-wallet#201]
No matter if you have received a transaction on the last address provided by "request coins", the next time you touch it, there is a new address provided. What if I touch it a thousand times?

Is there a pool of pre-generated addresses from the seed, or if not, isn't it possible to exceed the gap limit? And how much is the gap limit?

Scenario: you backup the wallet, touch request a thousand times, and receive coins on the 1001-th address provided. Wipe the phone, restore the backup, will the coins be visible?

**Comment by schildbach** [comment]
I'd be happy if you test it. (-:
What exactly are you afraid of?

In bitcoinj there is not really a gap limit. Instead, there is a prefetch size of 133 addresses (per chain). Details of this are best discussed on the bitcoinj mailing list.

**Comment by hrhristov** [comment]
I am afraid of the following scenario:

A user installs the app, makes a backup, and requests coins from N friends. The user loses the device. The first one and the last one of the friends send him some coins. The user restores the backup on another device, but he can see only the coins from the first friend, because the software does not scan all the N addresses. The user is not aware that he has more money, he transfers all that he can see and wipes the backup. The money are lost.

Now, if N is 10-100, this will not happen. But if N is more than 1000(or 133), this will happen.

Maybe N should be presented to the user and maybe he must be asked about it when restoring the backup?

Also, when requesting coins, isn't it better to show the same address if it's empty, the same way as when you touch the QR code in the main screen, it's always the same?

**Comment by schildbach** [comment]
Obviously we need to adjust parameters if there is a real problem. Currently, the app just isn't used like that. Who will have more than a few unpaid payment requests in a row?

In future, the app is supposed to keep payment requests, so that the user has an overview of if requests were paid or not. I can imagine this will make it easier to stay within the limits.

**Comment by luke-jr** [comment]
I think it's reasonable for the user to be expected to provide a "number of outstanding requests" upon recovering a seed-only backup. It's not like this should be a regular occurance.

**Comment by hrhristov** [comment]
If the app is supposed to keep payment requests, now I understand the logic of why a new address is generated every time. I think it's also reasonable to show a warning when the payment requests are beyond the prefetch size, to let the user know that he has to provide a number when recovering from a backup.

**Comment by schildbach** [comment]
I think the prefetch size is chosen large enough that there but not be such problem in practise. Thus I'm closing this issue.
