### ISSUE TITLE
restoring wallet issue

### ISSUE THREAD

**Issue by Carsiden** [schildbach/bitcoin-wallet#206]
Hi Andreas.

An accidental factory reset promted me to restore the back up. When choosing restore wallet from the secutity settings menu, the field for choosing the backup file is greyed out. Only the password field is open for edit. I have three backups neither of which can be opened from google docs by any app. How do I proceed?

**Comment by schildbach** [comment]
If Google Drive fails to open the document, you can always copy the backup file to /sdcard/Download/ on the phone and use Options > Safety > Restore wallet.

In future, please post support questions to the community: https://plus.google.com/communities/105515929887248493912
