### ISSUE TITLE
Provide the ability to share bitcoin wallet adress

### ISSUE THREAD

**Issue by Nolaan** [schildbach/bitcoin-wallet#207]
Hey,
It's very annoying when you need to send your wallet adress to a remote person, let's say via sms, that you have to go to a painful process instead of copy/paste !!!!

**Comment by schildbach** [comment]
What painful process?

Please don't use the clipboard, it's dangerous! https://plus.google.com/b/101256420499771441772/101256420499771441772/posts/dRAPrwhgLgF?cfem=1

For support questions, can you use the community?
