### ISSUE TITLE
Feature Request: Copy receiving address to clipboard

### ISSUE THREAD

**Issue by willsteel** [schildbach/bitcoin-wallet#209]
It would be really handy to have the address text String copied into the Android clipboard whenever a generated receiving address is shown to the user (QR popup). Currently you have to type the address when you have no optical usecase.

When you need someone else to send you money via chat, email, sms, ... there are tons of everyday reasons where you cant use the QR code directly.

**Comment by schildbach** [comment]
Using the clipboard for Bitcoin addresses is not recommended. See https://plus.google.com/101256420499771441772/posts/dRAPrwhgLgF

If you really need to copy an address to the clipboard, you can use Request coins, Copy action.
