### ISSUE TITLE
Security Enhancement: Spending PIN on address book

### ISSUE THREAD

**Issue by willsteel** [schildbach/bitcoin-wallet#210]
When a spending PIN is set an attacker can still edit the address book of a victim.

When people reuse addresses for each others frequently (as this is the nature of an address book), an attacker can quickly check if some addresses are used frequently and change those so the victim will send coins to the attacker the next time he uses his address book.

So either remove address book, because it doesn't fit for HD wallets anymore, or make spending PIN apply also on address book changes or opening of application itself.

**Comment by schildbach** [comment]
Interesting idea. Indeed the plan is to remove the address book at some time. It will be gradually replaced by a list of payment requests, which can be signed.

**Comment by schildbach** [comment]
Thinking more about this, addresses could be kept in all sorts of personal files and an attacker could modify them. The way to protect is set a screen lock and encrypt your device filesystem. Thus, I'm closing this issue.
