### ISSUE TITLE
Question: Matching HD Wallet Paths

### ISSUE THREAD

**Issue by pooleja** [schildbach/bitcoin-wallet#213]
I know the wallet is using Bitcoinj under the covers, and Bitcoinj says it is compatible with BIP32, but does it use the BIP44 hierarchy?

I have exported the extended public key, but I am unable to figure out what paths I should use to regenerate the matching receive addresses the app will use.

For example, if I use the exported extended public key, would the first receive address be generated from a path of "m/0/0/0" or "m/44'/0'/0'/0/0" or just "m/0"?

I would like to take this same extended public key and generate receive addresses in another service and be spendable from the wallet.

Thanks for any info!

**Comment by schildbach** [comment]
No it doesn't use BIP44. It uses BIP32-hierarchy, and of that only the "default account".

Can you ask support questions on the community? Thanks.
https://plus.google.com/communities/105515929887248493912

**Comment by pooleja** [comment]
OK, thanks.

**Comment by Klexx** [comment]
@pooleja I just imported my seed into electrum using path "m/0"

**Comment by yousifyou** [comment]
Please help me where can I use this code  "m/0" so as to recover seeds? And is there any other things to be done wiht it?  what I mean is like btc address,  xpub, and so?

**Comment by Klexx** [comment]
@yousifyou this may help: https://bitcointalk.org/index.php?topic=2061691.0
