### ISSUE TITLE
Backups on the same day get overwritten silently

### ISSUE THREAD

**Issue by langerhans** [schildbach/bitcoin-wallet#214]
Consider following scenario:

1. Backup your wallet
2. Reinstall app / delete data (I personally don't see the reason, but it happened)
3. Backup again (I mean, it *does* ask you to)

Step 3 will silently overwrite the backup created in step 1 as long as it happens on the same day, therefore losing all keys in it if you didn't archive the file. I'd have put in a PR, but I'm sick and yeah. In case I have time to do it before you, would you rather just add the time to the filename, or add a counter like `-001` until a non-existent file is found?

**Comment by schildbach** [comment]
Good catch, thanks! I'll see if I can come up with a fix tomorrow.

**Comment by schildbach** [comment]
Just fixed this via 9356b76ef2cd7bb7f80b3479cc1357cbcfa54a0e.
