### ISSUE TITLE
Hello! Can you help me to compile the mobile phone signature? Could you give me your BTC or remuneration

### ISSUE THREAD

**Issue by lvaluoliwei** [schildbach/bitcoin-wallet#215]
Hello! Friends, I am China user, I need a mobile phone terminal purse now, there have been Linux PC end of the purse and wallet
(my wallet address source code is: https://github.com/uncoin/uncoin)

If you can help me do the Android wallet, thank you very much, I will pay treasure to reward or bitcoin to you. Thank you very much
If you want you can add me QQ:2315637385

**Comment by schildbach** [comment]
For support questions can you join the community? https://plus.google.com/communities/105515929887248493912

**Comment by lvaluoliwei** [comment]
Thank you, hope you can help me develop the Android https://github.com/uncoin/uncoin wallet!
I'll give you a reward. Thank you!
