### ISSUE TITLE
Question: Is there any way to recover a lost PIN?

### ISSUE THREAD

**Issue by YahyaB** [schildbach/bitcoin-wallet#216]
I have the wallet password but I lost the PIN :-(
Heres what I tried:
I installed an older wallet version (I think 4.02) without the PIN function. Import of the wallet went fine, but after a day or so of synchronizing the App just crashed and can not be run again. Any idea?

**Comment by schildbach** [comment]
There is no PIN recovery, except trying all possible combinations if it wasn't too long.

Going back to old versions doesn't magically un-encrypt your wallet so it can't work. It will likely wreck your wallet however. So before trying to recover the PIN, make sure to upgrade to the latest version again and restore from your wallet backup.

Can you ask support questions on the community?
https://plus.google.com/communities/105515929887248493912
