### ISSUE TITLE
Recovery depends on Apache plugin?

### ISSUE THREAD

**Issue by jangos** [schildbach/bitcoin-wallet#219]
Due hardware error, I try to recover my wallet by https://github.com/schildbach/bitcoin-wallet/blob/master/wallet/README.recover

I get the "org.bitcoin.production" message and go for "RECOVERING FROM PROTOBUF WALLET FORMAT"

After
> cd bitcoinj/tools
> ./wallet-tool

I get 

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project bitcoinj-core: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :bitcoinj-core

What to do?

**Comment by schildbach** [comment]
Did you install Java? It should be installed with the "sudo apt-get install android-tools-adb openssl git maven" command mentioned in the readme.

Can you ask support questions in the community? https://plus.google.com/communities/105515929887248493912
