### ISSUE TITLE
After many transaction the wallet become completely unusable.

### ISSUE THREAD

**Issue by Transisto** [schildbach/bitcoin-wallet#220]
My phone just spend a whole day trying to display all of the 250+ transactions that happened to my address.  The wallet is extremely slow, it is still not clear if after two day of processing (leaving the phone on the charge) weather I will be able to move funds away.

Is anyone able to use this wallet with addresses having lets say 500 transactions ?
So far this has been the main reason why I'm not suggesting this wallet.

**Comment by schildbach** [comment]
It's not so much a matter of number of transactions, but more how many recipients these transactions pay to. Currently you should avoid receiving pay-to-many transactions. My personal wallet is 2000+ transactions and its speed is still tolerable.

Did you already upgrade to v4.23? It should speed up your wallet quite a bit. There is more improvement to come as soon as bitcoinj 0.13 is released and hopefully bitcoinj 0.14 fixes the problem entirely.

**Comment by schildbach** [comment]
This is a duplicate to https://github.com/schildbach/bitcoin-wallet/issues/158.
