### ISSUE TITLE
About other app to pull bitcoin-wallet

### ISSUE THREAD

**Issue by lanzf** [schildbach/bitcoin-wallet#221]
I think the bitcoin-wallet must add the interface（just URI） for other app to pull,you just add intent-filter like this in AndroidManifest.xml SendCoinsActivity
 \<intent-filter\>
        \<category android:name="android.intent.category.DEFAULT"/>
       \<action android:name="android.intent.action.VIEW" />
        \<data android:scheme="bitcoin" />
        \<data android:host="send" />
    \</intent-filter\>

and add getIntent in SendCoinsActivity to recive address and amount

**Comment by schildbach** [comment]
SendCoinsActivity already has intent filters very much like that. Can you describe your usecase? What is the android:host="send" supposed to mean? – looks invalid to me
