### ISSUE TITLE
How can I get the private key of my bitcoin address

### ISSUE THREAD

**Issue by radiumlau** [schildbach/bitcoin-wallet#222]
I can't find it on the Android Wallet, is there a way to get my own private key?
Thanks in advance.

**Comment by luke-jr** [comment]
Many modern wallets (I think including BW4A, someone correct me if I'm wrong) just have a single private key/seed for the whole wallet, not per address. Managing private keys is not safe for users in any case, mind you.

**Comment by radiumlau** [comment]
Hi,

If there's a single private key, where can I get it?
Does user have the right to see their own private key?

I used this Android wallet to send bitcoin to other crowdfunding project,
and the private key is the only proof, so I need it.



Thanks,
Radium Lau

On Wed, Apr 29, 2015 at 12:56 PM, Andreas Schildbach <
notifications@github.com> wrote:

> Closed #222 <https://github.com/schildbach/bitcoin-wallet/issues/222>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schildbach/bitcoin-wallet/issues/222#event-292668602>.
>



-- 
Thanks & Regards
Lei

**Comment by schildbach** [comment]
Such issues are best discussed on the community: https://plus.google.com/communities/105515929887248493912
Can you post there and explain the process of how you want to deliver the proof? Maybe we can find a way.
