### ISSUE TITLE
Translation string missing

### ISSUE THREAD

**Issue by Kirvx** [schildbach/bitcoin-wallet#223]
Hi :)

ADD LABEL TO YOUR ADDRESS is missing from Transifex.

**Comment by schildbach** [comment]
How do you mean it's missing? In what language?

**Comment by Kirvx** [comment]
This string is not present on Transifex to translate it in french.
https://i.imgur.com/DSnl8V5.png

**Comment by schildbach** [comment]
Can you search for the ID "edit_address_book_entry_dialog_title_add_receive"?
Transifex should sync the source language automatically.

**Comment by Kirvx** [comment]
I don't find the string in the source language :/

**Comment by schildbach** [comment]
Ok sorry, it should be there now. For some reason, Transifex didn't autosync any more from the source language.
