### ISSUE TITLE
Testnet3 sucking battery

### ISSUE THREAD

**Issue by xenog** [schildbach/bitcoin-wallet#224]
The Testnet3 app is sucking a lot of battery in my Nexus 4 with Android 5.1 since the app was updated to version 4.27. I am available to help troubleshoot if necessary.

**Comment by schildbach** [comment]
The reason is crazy miners mining like a block per second. It causes the timeout to never trigger.

**Comment by xenog** [comment]
Yeah, I was noticing the block counters changing quickly among my peers. I will uninstall Testnet3 then. Thanks for the quick answer.

**Comment by schildbach** [comment]
Yeah that's probably best if you don't need it.
