### ISSUE TITLE
Ubuntu Phone version

### ISSUE THREAD

**Issue by jangorecki** [schildbach/bitcoin-wallet#226]
Any plans to release Ubuntu Phone version? It uses MIR display driver, this should be only difference vs. ubuntu desktop environment.

**Comment by schildbach** [comment]
As soon as Ubuntu Phone can run Android apps (*), I'm all for it.

* I'm sure it's inevitable, even for Apple at some point

It's best to ask such questions in the community: https://plus.google.com/communities/105515929887248493912
