### ISSUE TITLE
mvn clean install

### ISSUE THREAD

**Issue by klevercoder** [schildbach/bitcoin-wallet#228]
[ERROR] Failed to execute goal on project wallet: Could not resolve dependencies for project de.schildbach.wallet:wallet:apk:4.30-test: Failed to collect dependencies at com.android.support:support-v4:aar:22.0.0: Failed to read artifact descriptor for com.android.support:support-v4:aar:22.0.0: Failure to transfer com.android.support:support-v4:pom:22.0.0 from file://${env.ANDROID_HOME}/extras/android/m2repository was cached in the local repository, resolution will not be reattempted until the update interval of android-support has elapsed or updates are forced. Original error: Could not transfer artifact com.android.support:support-v4:pom:22.0.0 from/to android-support (file://${env.ANDROID_HOME}/extras/android/m2repository): Repository path /extras/android/m2repository does not exist, and cannot be created. -> [Help 1]

**Comment by schildbach** [comment]
Go to the Android SDK Manager and make sure the Android Support Repository is installed.
