### ISSUE TITLE
SSLProtocolException when sweeping keys: "SSL23_GET_SERVER_HELLO"

### ISSUE THREAD

**Issue by DavidGriffith** [schildbach/bitcoin-wallet#232]
This error message is printed when attempting to swipe a private key in Electrum.  It contains .00219259 BTC.  My copy of Bitcoin Wallet is the latest one in the Google Play store.

![screenshot_2015-06-10-01-27-24](https://cloud.githubusercontent.com/assets/1289035/8078233/0d48f652-0f11-11e5-87f4-54caee38dbf6.png)

**Comment by schildbach** [comment]
How do you mean "in Electrum"? The screenshot is from Bitcoin Wallet, not Electrum. The error message stems from an SSL problem while connecting to biteasy.com (which is needed for querying the unspent outputs of that paper wallet). Is the error persistent? (I just checked and it worked for me.)

**Comment by DavidGriffith** [comment]
I have Electrum running on my Linux desktop and had it display the private key for an address that I want to sweep.  It displayed at QR code and when I scanned it on my phone, I got that error message.

**Comment by schildbach** [comment]
Ok, the issue is most likely not related to Electrum. Is it persistent?

**Comment by DavidGriffith** [comment]
Yes

**Comment by schildbach** [comment]
What happens if you access this link with the browser on your mobile device?
https://api.biteasy.com/testnet/v1/unspent-outputs

**Comment by wschildbach** [comment]
When I try to access it, I get a server answer but the ssl cert does not seem to be recognized.

**Comment by DavidGriffith** [comment]
I get the same, but the SSL certificate /is/ recognized.

**Comment by schildbach** [comment]
To both of you, what phone and Android version have you got?

(I wonder if this has to do with the aftermath caused by the [Logjam vulnerability](https://en.wikipedia.org/wiki/Logjam_%28computer_security%29).)

**Comment by DavidGriffith** [comment]
I use a Samsung Galaxy S5 (G900A) for use with AT&T networks.  Android version is 4.4.2.  The phone is rooted, if that matters.

**Comment by DavidGriffith** [comment]
A few hours ago I sent a few cents from my phone into a yet unused address created from the seed in my Electrum installation on a Linux box.  I was able to successfully sweep that private key.  The address that's giving me this trouble is one that I've been experimenting with repeatedly for a couple years.  There are 85 transactions on it.  Might that fact be tripping up bitcoin-wallet?

**Comment by schildbach** [comment]
Hard to imagine, but who knows? Would you be willing to share that paper wallet with me, after you swept it (using some other wallet)?

**Comment by DavidGriffith** [comment]
I emptied it by paying to an address on my phone.  Then attempting to sweep the private key worked worked as expected by telling me there was nothing in it.  Yes, you may have the private key.  Email coming.

**Comment by DavidGriffith** [comment]
Is there any news on this bug?

**Comment by Numerico** [comment]
I'm having this exact same issue when importing private keys.
It was working fine a month ago or so and suddenly this SSL handshake failure started happening.
If I try to browse to the bitaeasy api page I also get a connection error (could not establish a secure connection).
I'm on an Android phone too.
Can I help somehow?

**Comment by schildbach** [comment]
According to BitEasy, their sync will be finished today or early tomorrow.

**Comment by MiSKLaCH** [comment]
Error is still present nowadays. For your information, I cannot connect to https://api.biteasy.com/ with the default browser of my Android 4.4.2 smartphone, because of the SSLProtocolException error but, for example, it works with Chrome browser. Is there any chance to solve this issue from your side?

**Comment by schildbach** [comment]
Can you update to version 4.44 and try again? It should be fixed now, by using the BitEasy v2 API.

Direct download: https://github.com/schildbach/bitcoin-wallet/releases/tag/v4.44

**Comment by MiSKLaCH** [comment]
Do you mean the"*bitcoin-wallet-4.44.apk*" or the "
*bitcoin-wallet-4.44-test.apk*" file?
Because I upgraded to the first one.

**Comment by schildbach** [comment]
@MiSKLaCH The "-test" APK is for testnet. If your paper wallet is a mainnet wallet (very likely) then you've picked the right APK.

**Comment by MiSKLaCH** [comment]
Ok, I supposed this... so the bad news are that sweeping wouldn't work
yet... :(
Available for testing at your will! This IS and always will be my Android
bitcoin wallet of choice! ;)

**Comment by schildbach** [comment]
@MiSKLaCH What's happening? Can you attach your specific error message again?

**Comment by MiSKLaCH** [comment]
​
 Screenshot_2015-11-16-16-49-41.png
<https://drive.google.com/file/d/0B0O6jy-twlinc2xnMnI0RkdMNVU/view?usp=drive_web>
​
This is what I've got after trying to sweep a paper wallet with latest 4.44.

**Comment by schildbach** [comment]
Ok thanks. I forwarded your screenshot to BitEasy.

**Comment by Numerico** [comment]
Yes, I can confirm the issue is still happening for me too for v4.44 on Android.
Anything we can do on our side? 
If BitEasy didn't address it soon, could you consider changing it for another API or querying directly to the blockchain? Thank you.

**Comment by schildbach** [comment]
@Numerico Can you look up in your exception what's the exact text? You can post a screenshot if you want. We can offer an alternative API (my fav would be the Electrum protocol) but someone needs to do the implementation.

**Comment by MiSKLaCH** [comment]
It works now...

**Comment by schildbach** [comment]
Thanks! I'll close this as fixed.

**Comment by Numerico** [comment]
Yes, fixed!
