### ISSUE TITLE
Please add txn menu item to copy address to clipboard

### ISSUE THREAD

**Issue by bdimych** [schildbach/bitcoin-wallet#234]
in the list of transactions in the transaction menu there are 3 items:
-Add sending address
-Show QR code
-Browse

please add Copy Address, imho it is obvious functionality

**Comment by schildbach** [comment]
To me, it's not so obvious. Can you explain the whole usecase? Are you talking about incoming or outgoing transactions, or both?

**Comment by bdimych** [comment]
...yes, "address" is not so clear,
but "Copy Details" is clear,
both addresses + date + amount
?
