### ISSUE TITLE
With Coy Exchange takes the exchange rate? The ruble does not coincide with the real rate of exchange...

### ISSUE THREAD

**Issue by Earl777** [schildbach/bitcoin-wallet#235]
Good day! With Coy Exchange takes the exchange rate? The ruble does not coincide with the real rate of exchange...
The ruble in real time, on which we are working:
https://exmo.com/#?pair=BTC_RUB                      
https://btc-e.com/exchange/btc_rur

**Comment by schildbach** [comment]
Price is fetched from BitcoinAverage. Here are the markets: https://bitcoinaverage.com/markets#RUB
Note RUR is for the *old* ruble.

In future, please ask support questions like this on the community: https://plus.google.com/communities/105515929887248493912

**Comment by Earl777** [comment]
Thank you! I would contact the support.
According to the indicated BitcoinAverage also not the same ....

Спасибо! Буду обращаться в поддержку.
По указанному Вами BitcoinAverage тоже не совпадает....
