### ISSUE TITLE
Error !!! Does not meet the exchange rate!

### ISSUE THREAD

**Issue by Earl777** [schildbach/bitcoin-wallet#236]
Error !!! Strong does not meet the exchange rate in the program and website https://bitcoinaverage.com/markets#RUB in real time, listing in rubles, a very great loss !!!

Ошибка!!! Сильно не соответствует курс рубля в программе и сайтом https://bitcoinaverage.com/markets#RUB в реальном времени, при перечислении в рублях, очень большие потери!!!

**Comment by schildbach** [comment]
You need to be more specific. What do you see, where do you see it and what would you expect to see? If necessary you can use screenshots and highlight the important points.

The auto-translation is hard to understand, it would be useful if someone could provide a better translation.

**Comment by Earl777** [comment]
![img_20150610_181052_246](https://cloud.githubusercontent.com/assets/12829524/8086362/b1ca2804-0f9d-11e5-863f-7ea33586bfd8.jpg)
![img_20150610_181209_421](https://cloud.githubusercontent.com/assets/12829524/8086389/d7da790e-0f9d-11e5-9dd1-4a31771030e1.jpg)

Doesn't correspond to an appendix course, big losses when transfer in rubles!!!
Не соответствует курсу приложения, большие потери при переводе в рублях!!!

![screen](https://cloud.githubusercontent.com/assets/12829524/8086440/169bc95e-0f9e-11e5-96f5-7d3108d4dc3d.png)

**Comment by schildbach** [comment]
So 1 BTC is roughly 12800 RUB. Note it takes the 24h sliding average from BitcoinAverage, which is a bit higher than the last updates. Looks like the RUB is falling today.

**Comment by Earl777** [comment]
1 BTC - 24h sliding average	 -12711.09 RUB
1 BTC - last update: 18:51:05  -12441.66 RUB
1 BTC - Bitcoin Wallet              -12879.30 RUB

Because of a course difference, there are big losses when transfer in rubles It is very bad!
There is a wish for the closest course in real time....

Из-за разницы курса, идут большие потери при переводе в рублях -Это очень плохо!
Хочется максимально близкого курса в реальном времени....

**Comment by schildbach** [comment]
I just asked BitcoinAverage about why there is a ~100 RUB difference between the API and the web page. But that's under 1% of the price, so it's hardly a "big loss". Will keep this ticket updated when an answer arrives.

**Comment by Earl777** [comment]
1 BTC - Bitcoin Wallet -12879.30 RUB
+
1 BTC - last update: 18:51:05 -12448.07 RUB
=
1 BTC - 431 RUB

431 RUB * 20 BTC = 8620 RUB loss

At transfer in real time 20BTC loss 8620RUB ((((

При передачи в режиме реального времени 20BTC потеря 8620RUB

**Comment by Earl777** [comment]
1 BTC - Bitcoin Wallet -12879.30 RUB
+
1 BTC - last update: 18:51:05 -12448.07 RUB
=
1 BTC - 431 RUB

431 RUB * 20 BTC = 8620 RUB loss

At transfer in real time 20BTC loss 8620RUB ((((

При передачи в режиме реального времени 20BTC потеря 8620RUB

**Comment by schildbach** [comment]
I got an answer. The difference between the API and the web page is explainable by [global vs. local rates](https://bitcoinaverage.com/explain).
