### ISSUE TITLE
Not compatible with LG G2

### ISSUE THREAD

**Issue by Trudko** [schildbach/bitcoin-wallet#243]
For last few version (not sure which one) the app isn't compatible with my LG G2 (Android 4.4.2) and I have no idea why. What might be the problem?

**Comment by schildbach** [comment]
Never heard this before. What does "not compatible" mean? Is your device running the stock firmware?

**Comment by Trudko** [comment]
Yes and I have no idea what does it mean, Google play just says its not compatible. Btw I have updated to the latest version of the Android and so far same results.

**Comment by schildbach** [comment]
Ah, now I get it. You're likely running the Docomo version of the G2. We got an unusually high number of virtual machine crashes on that device so I banned it. I'm afraid if a firmware is so broken, coins can be lost.

If you feel adventurous, you can install the latest version from here: https://github.com/schildbach/bitcoin-wallet/releases/tag/v4.37

Let us know how it works. Don't put high amounts on that wallet, ok?

**Comment by AyeSarita** [comment]
Have you tried updating the phone firm software? ??

Usually that solves the problem

**Comment by schildbach** [comment]
I don't have a G2 so I can't test. I usually also can't talk to the users, because I only get anonymous crash reports from Google. And if the app crashes too early in startup the in-app crash reporter doesn't work.

**Comment by Trudko** [comment]
@AyeSarita yes I did  just today. Didn't help. 

@schildbach doesn't mean you've excluded Docom versions of G2 from supported phones and therefore Google Play lists it as unsupported? 

I did backed the wallet so I should be find shouldn't i?

**Comment by schildbach** [comment]
@Trudko Yes that's right.

**Comment by Trudko** [comment]
I see. Btw can I simply import it to different wallet app? I will need one anyway.

**Comment by schildbach** [comment]
No, the backup format is specific to the app. Have you tried installing from the link I posted? The easiest way to transfer your coins is via the app.

**Comment by Trudko** [comment]
not yet will try tomorrow. 

PS: How exactly did you excluded Docom version ? I am asking out of curiosity.

**Comment by Trudko** [comment]
In the end I've decided to switch to different wallet so I've used instructions from README.recover.
