### ISSUE TITLE
restore dialogue doesn't mention app name

### ISSUE THREAD

**Issue by paulboldra** [schildbach/bitcoin-wallet#244]
While attempting to open an unrelated password database via my file browser, the bitcoin-wallet restore window appeared. The problem was that there was no title on the restore window, so it was impossible to know what app was asking me for my password. Googling the dialogue message brought me here.

Please add "Bitcoin Wallet" or similar to the dialogue window.

**Comment by paulboldra** [comment]
Discovered it wasn't even bitcoin-wallet. It was dogecoin-wallet. Sorry, I have no idea if bitcoin-wallet has the same issue.

**Comment by schildbach** [comment]
Earlier versions of the app attached to the very generic content-type "application/octet-stream". I guess that's still in the dogecoin branch. Bitcoin Wallet now only attaches to its own content-type when it comes to opening files.
