### ISSUE TITLE
Problem with Bitcoin Wallet App from Play Store

### ISSUE THREAD

**Issue by libnara** [schildbach/bitcoin-wallet#246]
I was loading Bitcoin Wallet App from Play Store. Some data was loss from my mobile. Now I only have Adress Bitcoin : 1cwGwC6jHiPgRDxYEFWMkExjuuZZ6e78d 
So, I have not send money from my mobile and not show on my mobile when I have some money income. 
Check for me please. Some detail loss in my mobile. 
Now I'm not payment to someone.
How I will do now.

**Comment by schildbach** [comment]
Can you report an issue through the app? It's Options > Settings > Diagnostics > Report issue. Put your email address you're using for the report here so I can relate you.

**Comment by libnara** [comment]
I was loading Bitcoin Wallet App from Play Store. Some data was loss from my mobile. Now I only have Adress Bitcoin : 1cwGwC6jHiPgRDxYEFWMkExjuuZZ6e78d 
My Email : libnara@gmail.com
So, I have not send money from my mobile and not show on my mobile when I have some money income. 
Check for me please. Some detail loss in my mobile. 
Now I'm not payment to someone.
How I will do now.
