### ISSUE TITLE
Request amount of BTC - sent wrong amount, never showed up

### ISSUE THREAD

**Issue by fsm247** [schildbach/bitcoin-wallet#250]
Alright so here is my problem.
I downloaded the bitcoin wallet app from the play store today.
Then I clicked request money, did not enter an amount, just scanned the QR code and sent money to this QR code thinking that the money would arrive in my wallet.
The bitcoins didn't arrive however because I was probably supposed to enter a matching amount?!

I tested the wallet with another transfer to the QR code address that I see when opening the app and this transfer worked.

But what happened with the "requested" transfer I made? Hope I can recover the BTC somehow?

Thanks for any help.
Martin

**Comment by fsm247** [comment]
Oh the transfer just showed up about an hour later.
All good now :)

**Comment by schildbach** [comment]
Probably one of the parties was not connected to the Internet at the time of the payment. It helps to switch on Bluetooth on both sides, so that payments can be transmitted directly via the payment protocol.
