### ISSUE TITLE
Address changing should be optional

### ISSUE THREAD

**Issue by sssemil** [schildbach/bitcoin-wallet#252]

**Comment by Mr-Mondragon** [comment]
Why, in what situation would you ever *not* want to use HD addresses? (i.e. automatically change to new address upon every tx)

**Comment by sssemil** [comment]
When I want people on the other side to know my address :P

**Comment by luke-jr** [comment]
No, addresses are single-use tokens. If you reuse them you are at risk of loss, and harm both your own and others' privacy. It would be a bug for a wallet to not rotate them out when they're used...

**Comment by sssemil** [comment]
Ok :/

**Comment by Mr-Mondragon** [comment]
> When I want people on the other side to know my address :P

But they do. They can keep using the same address, if they want. The wallet only shows your most up to date, unused address. So for new transactions you can use that. But in fact, all previous address are still intact as well. If somebody sends bitcoins to one of your earlier addresses, it just ends up in your wallet as usual. 

The balance that your wallet shows, is not the balance on that single address you see (that address is typically empty) but on *all your addresses combined*.

**Comment by sssemil** [comment]
Oh, thanks for explaining.
