### ISSUE TITLE
Add "Sync only on Wi-Fi" option.

### ISSUE THREAD

**Issue by espress0** [schildbach/bitcoin-wallet#256]
Mobile data costs money. I tend to use Wifi to download/update apps.

**Comment by schildbach** [comment]
Go to Options > Settings > Data usage then either switch off mobile data entirely or restrict background data for individual apps.

Downloading/updating apps is done by the Play Store app.

**Comment by espress0** [comment]
I'm not talking about apk update. I'm talking about bitcoin's sync function(peer connection).
