### ISSUE TITLE
Version 4.40 receive double payment issue

### ISSUE THREAD

**Issue by chaosworld** [schildbach/bitcoin-wallet#259]
Don't know why double payment is receive then reverse one. It is wallet problem or bitcoin  block chain problem? It said "This  payment has been reversed by the sender"

**Comment by schildbach** [comment]
It's the ongoing malleability attack. Don't worry, only one of the two payments will confirm.

Please go to https://plus.google.com/communities/105515929887248493912 for user support.

**Comment by chaosworld** [comment]
Thank you!

On Mon, Oct 5, 2015 at 2:50 PM, Andreas Schildbach <notifications@github.com
> wrote:

> It's the ongoing malleability attack. Don't worry, only one of the two
> payments will confirm.
>
> Please go to https://plus.google.com/communities/105515929887248493912
> for user support.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schildbach/bitcoin-wallet/issues/259#issuecomment-145444674>
> .
>



-- 
*** Max ***
---
Victory Loves Preparation.
