### ISSUE TITLE
502 Bad Gateway on emptying paper wallet

### ISSUE THREAD

**Issue by inducer** [schildbach/bitcoin-wallet#260]
I get the following when trying to empty a paper wallet:

![screenshot_2015-10-20-13-01-21](https://cloud.githubusercontent.com/assets/352067/10616442/cc2d84bc-772a-11e5-9e6f-ebe59295dfe7.png)

Unfortunately, without the (malfunctioning) balance inquiry, it's not possible to specify the amount of bitcoins available, so it's not possible to use this function at all.

**Comment by schildbach** [comment]
Yes, it's a known problem. BitEasy is reindexing their database. They said it will be finished today or tomorrow.

**Comment by inducer** [comment]
It's been a while, and this hasn't gotten any better as far as I can tell.

**Comment by schildbach** [comment]
Indeed. They didn't finish yet unfortunately.

**Comment by inducer** [comment]
Good news: They're no longer 502'ing. Bad news: It's unclear that they're sending correct responses. (Or, it seems like that they aren't.--I got a zero balance when I don't think I should have.)

**Comment by schildbach** [comment]
Yes, currently their database seems to only contain the genesis block )-:

**Comment by inducer** [comment]
Now it says "Parse error: no value for is_spent".

**Comment by hrhristov** [comment]
Same here: "Parse error: no value for is_spent".
The paper wallet I'm trying to sweep is an old one and is not spent.

**Comment by schildbach** [comment]
I just released v4.44 which should fix this problem. It's on staged rollout, but if you want to skip the queue and download directly you can do so: https://github.com/schildbach/bitcoin-wallet/releases/tag/v4.44

Let us know if it worked for you.

**Comment by schildbach** [comment]
@hrhristov I'm not sure why BitEasy removed this property, it was certainly needed. However the new version is now accessing BitEasy's v2 API so it's not relevant any more.
