### ISSUE TITLE
how to sign a transaction-android wallet or bitcoinj

### ISSUE THREAD

**Issue by eeeark1** [schildbach/bitcoin-wallet#261]
I use the bitcoin wallet on my android device. I ran into a problem the other day though. Not the fault of the software by any means but I was hoping someone could help anyway. 

I made a payment to the wrong address, thankfully it ended up going to the same company. In order to retrieve my funds I need to sign a message from the same address that I sent from. I don't think this is possible with the android app (if I'm wrong, let me know). 
I thought it best to follow this guide: 

https://github.com/schildbach/bitcoin-wallet/blob/master/wallet/README.recover

I figured it would help me get my private key and I could then put that into electrum, or something I'm more comfortable with. I'm stuck here though. I can't find my private key in the output I get after

./wallet-tool dump --wallet=/tmp/bitcoin-wallet-decrypted-backup

How would one sign a message from bitcoinj? I'm really a noob here so I would need some very basic instruction. If this is too much to ask, could someone tell me how to get my private key out of what I have now? If this is the wrong place to ask such a question, I apologize. Thanks in advance.

**Comment by schildbach** [comment]
You could build such a feature into wallet-tool. It would be a welcome addition I think.

**Comment by eeeark1** [comment]
Mr. Schildbach,

While I'd be happy to try and help by building something such as this, I
have zero experience. I wouldn't even know where to begin such an endeavor.

Is there any way you could help me get my private key or point me in the
right direction?

**Comment by schildbach** [comment]
To just get your private key you can use the "dump" command like you said above, and combine it with the -dump-privkeys option.

I'm close this issue. Support questions are better asked on the G+ community: https://plus.google.com/communities/105515929887248493912
