### ISSUE TITLE
missing bitcoins

### ISSUE THREAD

**Issue by jonjones1** [schildbach/bitcoin-wallet#262]
Hi i transferred 0.18696 btc from another wallet i have on another devixe to this wallet i transferred to my address 1MwV2V8J71Rzg79ptbizqSj3T6K3FiFrZm , the transaction says it is complete from the side i sent it but nothing is showing up in this wallet it has seemed to disappear can you please help me asap i have tried to find the website or email to email but cant find nothing need help asap please contaxt me asap

I have tried contact developers and what not all im seeing is wrong email addresses and now have somehow ended here

**Comment by schildbach** [comment]
This page is not for user support. It's best to report an issue through the app, use Options > Settings > Diagnostics > Report issue. Make sure to include logs and the dump.
