### ISSUE TITLE
Wallet is Unstable on Galaxy S3

### ISSUE THREAD

**Issue by DotERM** [schildbach/bitcoin-wallet#264]
I am running the latest version of the wallet and, by some reason the wallet is so unstable, i go to settings menu and in 10 seconds it freezes, sometimes my phone also freezes, so i need to restart my phone. I could provide some info, just ask!

**Comment by schildbach** [comment]
This is not a support forum. Can you send an issue through the app?

**Comment by AyeSarita** [comment]
Actually it been happening  quiet frequently in my phone too and even my
email affect  by being  days late.
