### ISSUE TITLE
Widget height issue on Nexus 6 (1440x2560px)

### ISSUE THREAD

**Issue by bkimminich** [schildbach/bitcoin-wallet#266]
Widget looks twice/thrice as high as it should be and cannot be scaled vertically:

![Screenshot](https://dl.dropboxusercontent.com/u/42316604/2015-11-07%2021.34.35.png)

**Comment by schildbach** [comment]
Are you running the stock ROM on your Nexus 6? Have you got any hacks installed that are meant to change size of UI elements or fonts?

The widget is declaring a minHeight of 64dp. That should be the only factor affecting its vertical size.

**Comment by schildbach** [comment]
@bkimminich Can you do me a favor and try the following. Please add to your launcher one of the system widgets that is only one row high (e.g. the power manager that allows enabling/disabling WLAN, BT, etc). Please place it directly above the Bitcoin widget. Take a screenshot.

Now please turn your device to landscape. I read that for 6" devices, the launcher will actually adapt (enable auto-rotation). Take a screenshot again.

Please attach both screenshots to this issue.

**Comment by schildbach** [comment]
Ah, and please make sure the screenshots are without the "resize UI" like in the one you posted.

**Comment by bkimminich** [comment]
No, actually the phone doesn't go into landscape for the launcher, even with auto-rotate on. But here's the screenshot you asked for:

![Screenshot with 1x1 alongside](https://dl.dropboxusercontent.com/u/42316604/2015-11-08%2020.37.36.png)

**Comment by bkimminich** [comment]
Please also note that I am using Android 6.0 on my phone. I cannot say if this happened in any prior version, as I updated before installing most apps.

**Comment by schildbach** [comment]
Thanks, this will be fixed with the next release.
