### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by JasperWeiss** [schildbach/bitcoin-wallet#271]
Would it be possible to overhaul the design? Holo apps look pretty unproffesional these days and it's not very consistent with the rest of my phone. 
I suggest you guys look at OpenKeychain, the way they handle design and advanced information is very pleasent. I especially like their key backup process.(yes I know, Openkeychain is not related to bitcoin.)

**Comment by schildbach** [comment]
Closing because this is very unspecific.

**Comment by JasperWeiss** [comment]
Perhaps I should have been more specific.

Would it be possible to adjust this app to Google's Material Design guidelines.

**Comment by JasperWeiss** [comment]
@schildbach Is that specific enough? Do you need a link? https://www.google.com/design/spec/material-design/introduction.html

**Comment by schildbach** [comment]
The app is now using entirely material theme on Lollipop+.
