### ISSUE TITLE
Forgot wallet bitcoin pin

### ISSUE THREAD

**Issue by zulaiziey** [schildbach/bitcoin-wallet#282]
im having a problem when im doing transfer, the problem that im face is forget pin of the wallet. actually, im already make a backup for the wallet, balance still remain inside is 32mbtc. i need that bitcoin urgently to paid for someone. hopefully someone can help me about this. and i will give for backup data. thank you.

**Comment by schildbach** [comment]
We're afraid there is nothing we can do. You need to remember the PIN.
