### ISSUE TITLE
Dust transactions being produced?

### ISSUE THREAD

**Issue by bitcoinfees** [schildbach/bitcoin-wallet#283]
From [this comment](https://www.reddit.com/r/Bitcoin/comments/3xyxaa/3_days_stuck_transactions/) on reddit - apparently he managed to produce a tx with a 0.00001 BTC output, and that's probably the reason why his transaction is not being confirmed.

This is above the dust threshold for the old default minrelaytxfee of 0.00001 (546 satoshis), but falls short with respect to the new default of 0.00005 (2730 satoshis).

The dust limit probably needs to be dynamic as well.  The easiest way is perhaps to peg the dust limit to the transaction fee rate; i.e. assume that the network minrelaytxfee is equal to the tx fee rate that you are paying.

**Comment by schildbach** [comment]
Version 4.45 is already on staged rollout that increases the dust threshold.
