### ISSUE TITLE
Restoring wallet & decrypting from CLI fails

### ISSUE THREAD

**Issue by bnvk** [schildbach/bitcoin-wallet#289]
Upon trying to restore a backed up wallet on my Android phone, I received a message that said:

```
Wallet could not be restored:
Could not decrypt bytes
Bad password?
```

I checked and double checked the password I had written down. Same error. Upon searching, I found the command line option using openssl. I tried that approach and received the following error:

```
[user@vault ~]$ openssl enc -d -aes-256-cbc -a -in Android-Bitcoin-Wallet-backup-2015-06-29 > bitcoin-wallet-decrypted-backup
enter aes-256-cbc decryption password:
bad decrypt
140667725473648:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:609:
```

**Comment by schildbach** [comment]
Yes, that means the backup password is wrong.

**Comment by NetScr1be** [comment]
I got the same results in the same situation.

Is it possible there are disallowed characters? E.g. the period/dot or hash?

**Comment by bnvk** [comment]
@NetScr1be no Andreas was correct in this, as it was just my various Android backups + passwords being confused- classic PEBCAK error :P
