### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by schildbach** [schildbach/bitcoin-wallet#291]
v4.42/bitcoinj 0.13.3 introduced some performance regression, resulting in a significant level of ANRs.

**Comment by schildbach** [comment]
@langerhans suggested it might be commit 6e5059cdffe01682fb4e7b81c353d0fbbcc67567.

**Comment by schildbach** [comment]
@langerhans What do you think of eba6ef21c89a9d14afc2db01e8c0b83cfb733346 as a fix?

**Comment by langerhans** [comment]
I personally have throttled it to "Every 10th block, but for each block if blocksLeft is lower than 50". That way I was sure that the persisted height is actually the highest one. Wouldn't it be possible here that the chain sync ends in the throttle period and thus the persisted height is actually lower than the current chaintip?  
I pushed that version just 24h ago so the developer console doesn't tell much yet, but so far no ANRs. Sadle Google's cloud test lab seems to block most ports so I can't get peer connections on it :/

**Comment by schildbach** [comment]
The runnable will run at least once, no matter what. The only exception to this is when the VM is terminated early, but in this case you have many things to worry about. If 'best chain height ever' is not exact, it's not the end of the world: it can only cause the 'x hours behind' message to be off by a couple of hours.

**Comment by schildbach** [comment]
I didn't see any ANRs for the new version yet. So I consider this one fixed. Thanks Max for your help!

**Comment by schildbach** [comment]
A week later, no ANRs at all.

**Comment by langerhans** [comment]
I got 1, but it seems unrelated. The thread dump doesn't have a mention of SharedPreferences.
