### ISSUE TITLE
Users need to know your governance direction

### ISSUE THREAD

**Issue by jbash** [schildbach/bitcoin-wallet#292]
At this point, it would really help users to plan if you announced what you intend to do about the Bitcoin governance debate (and secondarily about the block size debate). Things have come to a head. Please either announce definitively that you will follow Classic, or Unlimited, or Core, or have multiple versions, or whatever, or explain exactly how and when you plan to make the decision.

A good place for that announcement would be in the descriptive text on Google Play. Another good place would be in the front page readme on Github.

Personal preference: follow Classic unless and until it becomes absolutely certain that it's going to fail.

**Comment by schildbach** [comment]
Being an SPV wallet, it always follows the longest block chain. SPV wallets are agnostic about block size.

There is no decision to be made between XT, Classic or Core, since those are all compatible to each other.

**Comment by luke-jr** [comment]
Note: Actual SPV wallets would accept a fraud proof showing the block is oversized, and reject the block. This wallet only ignores block size because it is not actually SPV.

**Comment by schildbach** [comment]
SPV = Simple Payment Verification = verification relies on verifying the PoW

How would an oversize check work? I know segwit introduces some possible proofs, but afaik oversize is not one of them.

**Comment by luke-jr** [comment]
It wouldn't be a small proof today. You'd need the midstate and last 64 bytes of the largest transactions (adding up to 1 MB). So the proof would probably be around 200kB. Once you get such a proof, you'd then flag the block as invalid.

**Comment by jbash** [comment]
OK, so proofs of fraud aside, you follow the longest block chain. That works until one or another fork decides to change the proof of work, or something else that can be noticed in the block header.

The main issue here isn't block size. It's governance process. The question is whose governance process you're going to treat as legitimate when they come into conflict in a way your code cares about.

**Comment by luke-jr** [comment]
@jbash Bitcoin has no governance process at all. Those who try to impose one are just deluding themselves.
