### ISSUE TITLE
transaction history export!

### ISSUE THREAD

**Issue by Codes4Fun** [schildbach/bitcoin-wallet#298]
It's tax season and I noticed that sometime ago the wallet started using hidden addresses for change.

It would be nice then to have a way to either export the transaction history of my wallet directly, or be able to export a list of addresses my wallet uses.

I am able to manually track down these change addresses via block explorer but this has made it less automated to accumulate transactions for taxes. And maybe for other people who have done lots of transactions this will be an incredibly difficult way of doing it.

This is also kind of freaked me out because when I went to blockexplorer and saw a lower balance than the app was reporting, I thought my bitcoins were stolen!

**Comment by Codes4Fun** [comment]
If it is done as a transaction export it would be nice to also have the blockchain txid. This way transferring bitcoins between my wallets (buying a new phone and transfering my bitcoins for example) can be merged into a single transaction (with the fee as the cost) instead of becoming separate spend/acquire transactions.

**Comment by Codes4Fun** [comment]
I added a bounty to this issue
https://www.bountysource.com/issues/30424337-transaction-export

**Comment by schildbach** [comment]
See #34.

**Comment by schildbach** [comment]
You can export your xpub which can be used to reconstruct your tx history.

**Comment by Codes4Fun** [comment]
#34 seems to have a different end user requirement which is why you proposed a slightly different solution on that ticket.

With my issue, I would just want the transaction history without having to include private keys. What is proposed for #34 seems like a dangerous solution for this specific issue, as it includes more data than the user requires, which if the user is not careful they could end up with their bitcoins stolen.

xpub sounds like it might work but I can't seem to find good documentation on how to export and use it. I'll dig around more for that.

Thanks.

**Comment by Codes4Fun** [comment]
I figured out how to export and use xpub, thanks for the tip!!!! Although I do see one peculiar thing, my first derived child of externalParentKey was unused! I think this is because I had my wallet since before HD Wallets were added and so when I created keys afterwards the issuedExternalKeys were offset for my pre-existing key.

Thanks Again!
